USE INEURON_ASSIGNMENT_DB;

----------------------------------------------------------------🎯Analyzing Road Safety in the UK--------------------------------------------------------------------------------

CREATE OR REPLACE TABLE PK_ACCIDENTS_2015(
	ACCIDENT_INDEX VARCHAR(20),
    ACCIDENT_SEVERITY INT
    );
    
SELECT * FROM PK_ACCIDENTS_2015;

CREATE OR REPLACE TABLE PK_VEHICLES_2015 (
	ACCIDENT_INDEX VARCHAR(20),
    VEHICLE_TYPE INT
    );
    
SELECT * FROM PK_VEHICLES_2015;

-- DROP TABLE PK_VEHICLE_TYPE;
CREATE OR REPLACE TABLE PK_VEHICLE_TYPE (
	VEHICLE_CODE INT,
    LABEL VARCHAR(100)
    );

SELECT * FROM PK_VEHICLE_TYPE;

-- DATA IS LOADED FROM SNOWLFLAKE

-- 1. Evaluate the median severity value of accidents caused by various Motorcycles.

SELECT VT.LABEL, MEDIAN(A.ACCIDENT_Severity) AS Median_Severity
FROM PK_ACCIDENTS_2015 A
JOIN PK_VEHICLES_2015 V ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN PK_Vehicle_type VT ON V.VEHICLE_TYPE = VT.VEHICLE_CODE
WHERE VT.LABEL LIKE 'Motorcycle%'
GROUP BY 1;


-- 2. Evaluate Accident Severity and Total Accidents per Vehicle Type

SELECT VT.LABEL AS "VEHICLE_TYPE", A.ACCIDENT_SEVERITY AS "SEVERITY", COUNT(A.ACCIDENT_INDEX) AS TOTAL_ACCIDENTS 
FROM PK_ACCIDENTS_2015 A
JOIN PK_VEHICLES_2015 V ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN PK_VEHICLE_TYPE VT ON V.VEHICLE_TYPE = VT.VEHICLE_CODE
GROUP BY 1,2
ORDER BY 1;

-- 3. Calculate the Average Severity by vehicle type.

SELECT VT.LABEL AS "VEHICLE TYPE", AVG(A.ACCIDENT_SEVERITY) AS "AVERAGE SEVERITY"
FROM PK_ACCIDENTS_2015 A
JOIN PK_VEHICLES_2015 V ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN PK_VEHICLE_TYPE VT ON V.VEHICLE_TYPE = VT.VEHICLE_CODE
GROUP BY 1
ORDER BY 2;

-- 4. Calculate the Average Severity and Total Accidents by Motorcycle.

SELECT VT.LABEL AS "MOTORCYCLE", AVG(A.ACCIDENT_SEVERITY) AS "AVERAGE SEVERITY", COUNT(A.ACCIDENT_INDEX) AS "TOTAL ACCIDENTS"
FROM PK_ACCIDENTS_2015 A
JOIN PK_VEHICLES_2015 V ON A.ACCIDENT_INDEX = V.ACCIDENT_INDEX
JOIN PK_VEHICLE_TYPE VT ON V.VEHICLE_TYPE = VT.VEHICLE_CODE
WHERE VT.LABEL LIKE '%Motorcycle%'
GROUP BY 1
ORDER BY 2,3;
